### ISSUE TITLE
Revamp README.md orienting it to deployment/usage and extract dev instructions

### ISSUE THREAD

**Issue by unleashed** [3scale/apisonator#27]
The current README file is heavily oriented towards developers / contributors, but it barely has information on how to deploy and use Apisonator. We can split both aspects and have a README that is more oriented towards new users installing and using the software. We also have broken links to documentation in the old 3scale website.

I think it would be good to have a look at it from the point of view of a user wanting to install and start using it (even if we suppose they are not acquainted with the rest of the 3scale platform or just want to test or push data to the Redis database).

**Comment by unleashed** [comment]
This should also now refer to `pisoni` as opposed to `3scale_core`. /cc @3scale/backend anyone?

**Comment by miguelsorianod** [comment]
This was done on #33. I close the issue.
