### ISSUE TITLE
Drop support for Ruby 2.4 (when possible)

### ISSUE THREAD

**Issue by davidor** [3scale/apisonator#303]
We can't do this yet, but when possible, we should drop support for Ruby 2.4.
After that, we'll be able to update some gems like the async ones.

**Comment by andrewdavidmackenzie** [comment]
Can you describe what's keeping us on ruby 2.4, so we have a clearer definition of the dependency/tasks that would allow us to drop it?

I understand it is the current version of ruby deployed in VMs on legacy infra, no?
So, when we move listeners to OCP Production then we should be able to drop it, no?

**Comment by davidor** [comment]
Yes, that's it.

**Comment by unleashed** [comment]
Waiting on @3scale/operations to confirm the demise of Ruby 2.4 before upgrading.

**Comment by slopezz** [comment]
Legacy backend infra was decommissioned one month ago, so you can proceed with the upgrade @unleashed

**Comment by eguzki** [comment]
closed with #309
