### ISSUE TITLE
Development environment based on docker compose. Remove CI image

### ISSUE THREAD

**Issue by eguzki** [3scale/apisonator#354]
- Support only one ruby version
- Separated containers for tweemproxy and sentinels
- Separated contatiners for redis. New redis version. Maybe 6.2??

**Comment by eguzki** [comment]
ideally yes. More aligned with the company tech stack. That being said, facing the real world, if you can make it happen with podman, be my guest. We tried in the past in the APIcast repo https://github.com/3scale/APIcast/pull/1353 and failed miserably.

**Comment by jlledom** [comment]
I use podman for docker-compose files locally and it works fine. Not sure if that will work for people using Mac, though.

**Comment by eguzki** [comment]
what is Mac?  :trollface:

**Comment by jlledom** [comment]
Closed by https://github.com/3scale/apisonator/pull/370
