### ISSUE TITLE
Delete stats endpoint must not accept endusers

### ISSUE THREAD

**Issue by eguzki** [3scale/apisonator#85]
Currently, delete stats endpoint
> DELETE /internal/services/#{service_id}/stats

Accepts as request body
```json
{ 
  "deletejobdef": {
     "applications": ["1"],
     "metrics": ["5"],
     "from": 1483228800,
     "to": 1483228800, 
     "users": []
  }
}
```

The list of endusers `users` exists only in apisonator database. Porta client does not have list of end users. Moreover, Apisonator does not have internal endpoint te get list of `endusers`.

So, requested change is:
* Remove `users` from request body 
* Get the list of endusers internally using method ` ThreeScale::Backend::User.service_users_set_key(service_id)` when delete stats endpoint is called and pass the list to stats key generator.

**Comment by davidor** [comment]
The new endpoint does not accept end-users so I'll close this one.
