### ISSUE TITLE
Undefined dependencies for running apisonator.

### ISSUE THREAD

**Issue by whitingjr** [3scale/apisonator#95]
Hi,
 I am attempting to test the apisonator project on Fedora 28.
 The [Running tests](https://github.com/3scale/apisonator/blob/master/DEVELOPMENT.md#running-tests) suggests using the script 
`$ script/test`
 But I am finding this script is expecting some tools/software in the /opt directory (amongst other locations).
 I would have expected the documentation on testing to have listed the following as dependencies
- Redis
- PostgreSQL
- Nutcracker

 Do you agree ?

**Comment by davidor** [comment]
Hi @whitingjr ,

Are you using the development docker image?

If you are using it, those tools should already be installed. The script that you mentioned takes care of starting all the dependencies: https://github.com/3scale/apisonator/blob/fbf22506249ce485b9847aac543b4c9493f89f98/script/test#L46

**Comment by whitingjr** [comment]
@davidor ok that's maybe where I am going wrong. I was not using the dev image. I am happy for this issue to be closed.

**Comment by unleashed** [comment]
:+1:
